name: food_delivery
description: "A fast and convenient food delivery application with a wide selection of food"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.7
  collection: ^1.19.1
  curved_navigation_bar: ^1.0.6
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.1.0
  intl: ^0.20.2
  lottie: ^3.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/icon_logo.png"
  adaptive_icon_foreground: "assets/img/icon_logo.png"
  adaptive_icon_background: "#ffffff"

flutter:
  assets:
    - assets/img/
    - assets/lottie/
    - assets/img/burgers/
    - assets/img/deserts/
    - assets/img/drinks/
    - assets/img/salads/
    - assets/img/sides/
  uses-material-design: true
